# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
# codex start
# codex (old code) minecraft_version=26.3
minecraft_version=26.2
# codex end
loader_version=0.19.5
# Mod Properties
# codex start
# codex (old code) mod_version=1.0.0+26.3
mod_version=1.0.0+26.2
# codex end
maven_group=com.memeasaur
archives_base_name=StatusEffectHud-fabric
# Dependencies
# check this on https://modmuss50.me/fabric.html
# codex start
# codex (old code) fabric_version=0.161.0+26.3
fabric_version=0.161.0+26.2
# codex end
